name: tdiff
base: core18
version: '0.2.0'
summary: CLI application for comparing JSON and YAML files
description: |
  This program is intended for comparing YAML and/or JSON files, indicating
  differences in data, which can be useful when keys are out of order or simply
  you want to automate the comparson.

grade: devel
confinement: strict

apps:
  tdiff:
    command: bin/tdiff

parts:
  tdiff:
    source: "./"
    plugin: crystal