name: CI

on:
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 21 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba
  test_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --order random --error-on-warnings
  test_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: nightly
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --order random --error-on-warnings