name: Deployment

on:
  release:
    types:
      - created

jobs:
  dist_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: oprypin/install-crystal@v1
    - name: Build
      run: crystal build src/tdiff.cr
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./tdiff.exe
        asset_name: tdiff-${{ github.event.release.tag_name }}-windows-x86_64.exe
        asset_content_type: binary/octet-stream

  dist_linux_snapcraft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
    - name: Build Snap
      run: snapcraft
    - name: Publish snap
      run: snapcraft push --release=beta *.snap

  dist_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Update Libs
      run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev
    - name: Build
      run: |
        shards build --production --release --static --no-debug
        strip ./bin/tdiff
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/tdiff
        asset_name: tdiff-${{ github.event.release.tag_name }}-linux-x86_64
        asset_content_type: binary/octet-stream
  deploy_docs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: crystal docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs